language: csharp
install:
  - nuget restore dotnet/csharp.sln
  - nuget install NUnit.Runners -Version 3.0.1 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release dotnet/csharp.sln
  - mono ./testrunner/NUnit.Console.3.0.1/tools/nunit3-console.exe ./dotnet/csharp/bin/Release/csharp.dll
